export interface DemoNode {
  id: string;
  parentId: string | null;
  chosenLabel: string | null;
  chosenType: "safe" | "risky" | "emotional" | "chaotic" | null;
  text: string; // Story prose for reading panel
  wordCount: number;
  startsChapter: boolean;
}

export interface DemoTree {
  title: string;
  nodes: DemoNode[];
}

// ── hero: "The Pale Book" (7 nodes, 2 branches from root) ────────────
// Root text matches the landing page hero content exactly.
const heroNodes: DemoNode[] = [
  {
    id: "hero-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "Kael descended the slick stone steps, lantern swaying. The air tasted of iron and forgotten things. The passage opened into a vast chamber. In the center — a book bound in pale leather that seemed to breathe.",
    wordCount: 37,
    startsChapter: true,
  },
  {
    id: "hero-2a",
    parentId: "hero-1",
    chosenLabel: "Open the book carefully",
    chosenType: "safe",
    text: "Kael lifted the cover with both hands, treating it like something sacred. The pages were blank — then, slowly, ink bled upward from the binding and words formed as if remembering themselves.",
    wordCount: 32,
    startsChapter: false,
  },
  {
    id: "hero-2b",
    parentId: "hero-1",
    chosenLabel: "Read the incantation aloud",
    chosenType: "risky",
    text: "The words came before he could stop them, drawn from his throat like a hook pulling a fish from still water. The lantern flame turned violet. Something in the walls began to listen.",
    wordCount: 33,
    startsChapter: false,
  },
  {
    id: "hero-3a",
    parentId: "hero-2a",
    chosenLabel: "Follow the ink to its source",
    chosenType: "emotional",
    text: "The text described his sister — her name, her last morning, the way she hummed while braiding her hair. He had not spoken of her in three years. His hands would not stop shaking.",
    wordCount: 34,
    startsChapter: false,
  },
  {
    id: "hero-3b",
    parentId: "hero-2a",
    chosenLabel: "Tear out the first page",
    chosenType: "chaotic",
    text: "The page tore cleanly, too cleanly, as though it had been waiting. A sound like breath escaped the spine. Where the page had been, a map now glowed in the binding — a map of somewhere underground.",
    wordCount: 37,
    startsChapter: false,
  },
  {
    id: "hero-3c",
    parentId: "hero-2b",
    chosenLabel: "Let the words finish",
    chosenType: "risky",
    text: "The incantation ended and silence crashed in like a wave. A figure stood on the far side of the chamber where there had been only stone. It wore his face, but it was older, and it was afraid.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "hero-3d",
    parentId: "hero-2b",
    chosenLabel: "Slam the book shut",
    chosenType: "safe",
    text: "The snap of the covers echoed like a gunshot. The violet flame died. Kael stood in ordinary darkness, heart hammering, the book cold under his palms — and somewhere behind the walls, something moved away.",
    wordCount: 35,
    startsChapter: false,
  },
];

// ── features: "The Letter" (13 nodes, 4 branching parents) ───────────
// A mystery/suspense story about a photograph.
const featuresNodes: DemoNode[] = [
  {
    id: "feat-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "The photograph arrived in an envelope with no return address. Mara turned it over in the kitchen light: herself, from behind, standing at a window she did not recognise. The date stamped on the back was tomorrow.",
    wordCount: 37,
    startsChapter: true,
  },
  {
    id: "feat-2a",
    parentId: "feat-1",
    chosenLabel: "Call the number on the envelope",
    chosenType: "safe",
    text: "Three rings and then static. A voice — calm, unhurried — said: you are not supposed to see that. The line cut before she could respond. She stood with the receiver against her shoulder for a long time.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "feat-2b",
    parentId: "feat-1",
    chosenLabel: "Drive to the street in the photo",
    chosenType: "risky",
    text: "She recognised the building at the corner of Ninth and Crale — she had passed it a hundred times. The window on the third floor was lit. Someone stood behind the glass, watching the street. Watching for her.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "feat-3a",
    parentId: "feat-2a",
    chosenLabel: "Research the stamp code",
    chosenType: "safe",
    text: "The postmark code routed back to a sorting facility that had been closed for eleven years. The facility had processed mail for a single corporate client: a biometrics firm that no longer existed under that name.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "feat-3b",
    parentId: "feat-2a",
    chosenLabel: "Show the photo to her neighbour",
    chosenType: "emotional",
    text: "Old Emil studied it under his reading lamp without speaking. Then: I took this, he said. But not of you — of my daughter, forty years ago. She looked exactly like you. He began to cry.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "feat-3c",
    parentId: "feat-2b",
    chosenLabel: "Enter the building",
    chosenType: "risky",
    text: "The lobby was unlocked and smelled of fresh paint over something older. A directory on the wall listed one tenant on the third floor: M. Voss, Consultant. Her own surname. Her own initial. Her stomach dropped.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "feat-3d",
    parentId: "feat-2b",
    chosenLabel: "Photograph the window in return",
    chosenType: "chaotic",
    text: "She raised her phone. The figure behind the glass raised one too — the movement a perfect mirror. The flash fired. The figure was gone. When she checked the image, the window was empty.",
    wordCount: 34,
    startsChapter: false,
  },
  {
    id: "feat-4a",
    parentId: "feat-3a",
    chosenLabel: "Follow the corporate trail",
    chosenType: "safe",
    text: "Three shell companies later, the trail ended at a man named Dravec, who had run a behavioural prediction project for a government office that officially did not exist. His last known address was her building.",
    wordCount: 35,
    startsChapter: false,
  },
  {
    id: "feat-4b",
    parentId: "feat-3a",
    chosenLabel: "Burn the photograph",
    chosenType: "chaotic",
    text: "The paper caught and curled and smelled of nothing. She felt nothing either — until the smoke alarm triggered and she looked up and saw a second envelope had been slid under her door while she was distracted.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "feat-4c",
    parentId: "feat-3c",
    chosenLabel: "Knock on the door",
    chosenType: "emotional",
    text: "No answer. She tried the handle — unlocked. Inside: a desk, a chair, a monitor showing a live feed of her own apartment. On the desk, a note in her handwriting that she had never written: leave before midnight.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "feat-4d",
    parentId: "feat-3c",
    chosenLabel: "Check the building records",
    chosenType: "safe",
    text: "The lease began ten years ago and was renewed automatically. The guarantor on the original contract was a woman named Mara Voss — her own birth year, her mother's maiden name, her blood type listed correctly.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "feat-4e",
    parentId: "feat-3d",
    chosenLabel: "Send the empty photo to the number",
    chosenType: "risky",
    text: "She texted the image to the number that had gone silent. A reply came in seconds: an address, a time, and three words — you already know. The timestamp on the text showed it had been sent yesterday.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "feat-4f",
    parentId: "feat-3b",
    chosenLabel: "Ask Emil what happened to his daughter",
    chosenType: "emotional",
    text: "She disappeared in this neighbourhood, he said. The police found only a photograph — taken from behind, at a window. He had not spoken of it in years. He held out a photograph now: Mara, from behind, at her own window.",
    wordCount: 41,
    startsChapter: false,
  },
];

// ── fantasy: "The Oath of Embers" (6 nodes, 2 branches) ──────────────
const fantasyNodes: DemoNode[] = [
  {
    id: "fan-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "The dragon's oath was carved into the mountain's heart and every child in the valley was taught its terms. Seren had memorised the words without understanding why they frightened her mother. Now the mountain was glowing.",
    wordCount: 36,
    startsChapter: true,
  },
  {
    id: "fan-2a",
    parentId: "fan-1",
    chosenLabel: "Climb toward the glow",
    chosenType: "risky",
    text: "The path was older than the village, worn by feet and claws in equal measure. Halfway up, the carved oath caught the light — and one word was wrong. It had not been wrong the last time she looked.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "fan-2b",
    parentId: "fan-1",
    chosenLabel: "Wake the village elder",
    chosenType: "safe",
    text: "Elder Corvin answered the door as if he had been waiting. He looked past her toward the mountain and said: so the terms have finally lapsed. He was already pulling on his coat. He did not look surprised.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "fan-3a",
    parentId: "fan-2a",
    chosenLabel: "Read the altered word aloud",
    chosenType: "chaotic",
    text: "The syllable cracked across the mountain face like a whip. The glow doubled, then died. In the ringing silence, something very large exhaled above the treeline — and a voice said: it has been a long wait, young keeper.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "fan-3b",
    parentId: "fan-2a",
    chosenLabel: "Search for the original text",
    chosenType: "emotional",
    text: "Her mother had pressed paper rubbings of the oath into a book and hidden it under the hearthstone. Seren found them with shaking hands. The rubbing was different from both the current carving and her memory. Someone had changed it twice.",
    wordCount: 41,
    startsChapter: false,
  },
  {
    id: "fan-3c",
    parentId: "fan-2b",
    chosenLabel: "Ask what the lapsed terms mean",
    chosenType: "emotional",
    text: "Corvin sat across from her and folded his hands. The oath was a trade, he said. The dragon kept the cold away and we kept a secret for it. The secret is yours now. Your family has kept it for six generations.",
    wordCount: 42,
    startsChapter: false,
  },
  {
    id: "fan-3d",
    parentId: "fan-2b",
    chosenLabel: "Refuse the burden and walk away",
    chosenType: "risky",
    text: "She turned from his door without answering. Behind her, the mountain groaned. The glow pulsed once, brighter, then dimmed. By the time she reached the village square, the first frost in living memory was forming on the well.",
    wordCount: 38,
    startsChapter: false,
  },
];

// ── scifi: "Signal from the Fold" (6 nodes, 2 branches) ──────────────
const scifiNodes: DemoNode[] = [
  {
    id: "sci-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "The distress beacon was eleven light-years old and still transmitting. Navigation Officer Priya Osei pulled it up on the secondary display: the signal source was the dead system their colony ship had been diverted to avoid. No one explained why.",
    wordCount: 40,
    startsChapter: true,
  },
  {
    id: "sci-2a",
    parentId: "sci-1",
    chosenLabel: "Trace the beacon's origin point",
    chosenType: "safe",
    text: "The origin co-ordinates resolved to a station that did not appear on any chart issued after 2241. Cross-referencing older archives, she found a single entry: Waypoint Havel, decommissioned, reason redacted. The redaction was authorised by the mission's own charter.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "sci-2b",
    parentId: "sci-1",
    chosenLabel: "Broadcast a response",
    chosenType: "risky",
    text: "The automated reply arrived in 0.003 seconds — far too fast for eleven light-years. The message was a crew manifest. Every name on it belonged to someone already aboard her ship. Her own name was listed twice.",
    wordCount: 37,
    startsChapter: false,
  },
  {
    id: "sci-3a",
    parentId: "sci-2a",
    chosenLabel: "File a report with Command",
    chosenType: "safe",
    text: "Command's response came back with a priority flag she had never seen before: SEQUESTER. Her terminal locked. Over the intercom, the Captain's voice — steady, rehearsed — told the crew to proceed to assigned quarters immediately.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "sci-3b",
    parentId: "sci-2a",
    chosenLabel: "Access the redacted file",
    chosenType: "chaotic",
    text: "Three encryption layers and she was through. The file was a debrief from a mission that matched their trajectory exactly — same route, same stops, same cargo. The mission date was forty years in the future.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "sci-3c",
    parentId: "sci-2b",
    chosenLabel: "Find the second version of herself",
    chosenType: "emotional",
    text: "She checked the crew manifest against bunk assignments. Bay 14 was listed as occupied by a Priya Osei — but Priya Osei was standing in the corridor outside it. She pressed her palm to the door panel and it recognised her.",
    wordCount: 41,
    startsChapter: false,
  },
  {
    id: "sci-3d",
    parentId: "sci-2b",
    chosenLabel: "Delete the manifest and deny everything",
    chosenType: "chaotic",
    text: "She wiped the file and cleared the transmission log. For eleven seconds, the bridge was quiet. Then the beacon resumed — louder, closer. The new message was one line: deletion acknowledged. Adjusting course to intercept.",
    wordCount: 35,
    startsChapter: false,
  },
];

// ── mystery: "The Missing Hour" (6 nodes, 2 branches) ────────────────
const mysteryNodes: DemoNode[] = [
  {
    id: "mys-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "Detective Lena Cole had worked missing-persons cases for twelve years and she had never seen a file like this one: the victim had vanished between two CCTV frames, one second apart, in an empty corridor with no exits.",
    wordCount: 38,
    startsChapter: true,
  },
  {
    id: "mys-2a",
    parentId: "mys-1",
    chosenLabel: "Review the footage frame by frame",
    chosenType: "safe",
    text: "Frame 8,441: Dr. Harrowfield walking alone. Frame 8,442: the corridor empty. No blur. No cut in the timestamp. She played it six times and the result was always the same. The man had simply ceased to be there.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "mys-2b",
    parentId: "mys-1",
    chosenLabel: "Interview the last witness",
    chosenType: "emotional",
    text: "The janitor had been mopping the adjacent hallway. He did not look up when Cole entered. He said: I heard him knock on the wall three times — fast, like a signal. Then nothing. He crossed himself and went back to mopping.",
    wordCount: 42,
    startsChapter: false,
  },
  {
    id: "mys-3a",
    parentId: "mys-2a",
    chosenLabel: "Check the building's structural plans",
    chosenType: "safe",
    text: "The plans showed nothing unusual until she compared the 1987 originals with the 2019 renovation permits. A room had been walled over — unmarked, unventilated, roughly the size of a large closet. It was directly behind the camera's blind spot.",
    wordCount: 40,
    startsChapter: false,
  },
  {
    id: "mys-3b",
    parentId: "mys-2a",
    chosenLabel: "Pull Harrowfield's phone data",
    chosenType: "risky",
    text: "His last text was sent at 14:07:59 — one second before he vanished on camera. The recipient was a number not registered to any carrier. The message was four words: it worked, I'm through.",
    wordCount: 34,
    startsChapter: false,
  },
  {
    id: "mys-3c",
    parentId: "mys-2b",
    chosenLabel: "Trace the knocking pattern",
    chosenType: "chaotic",
    text: "Three quick knocks. She had heard that pattern before — in a cold case from 2011, a different building, a different corridor. The victim in that case had also vanished between camera frames. That case was still open.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "mys-3d",
    parentId: "mys-2b",
    chosenLabel: "Search the wall where he knocked",
    chosenType: "risky",
    text: "She ran her hands along the plaster until she felt it — a seam, painted over, barely visible. Behind it the wall sounded hollow. She pressed three times, fast. Something clicked. The wall moved inward half an inch.",
    wordCount: 38,
    startsChapter: false,
  },
];

// ── romance: "One Platform Apart" (6 nodes, 2 branches) ──────────────
const romanceNodes: DemoNode[] = [
  {
    id: "rom-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "They had missed the same train every Thursday for a month — she always two minutes late, he always waiting on the wrong platform. She had memorised his jacket. He had memorised the way she read with the book tilted slightly left.",
    wordCount: 42,
    startsChapter: true,
  },
  {
    id: "rom-2a",
    parentId: "rom-1",
    chosenLabel: "Ask about his book",
    chosenType: "safe",
    text: "She had not meant to say anything. The words came out anyway: is that any good? He looked up startled, then embarrassed, then something softer. He said: honestly I've been reading the same page for three weeks. She laughed.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "rom-2b",
    parentId: "rom-1",
    chosenLabel: "Miss the train again on purpose",
    chosenType: "emotional",
    text: "She watched the doors close from the platform. Her heart was doing something undignified. He watched the train leave and turned to find her still standing there and his expression shifted through surprise and into something careful and warm.",
    wordCount: 39,
    startsChapter: false,
  },
  {
    id: "rom-3a",
    parentId: "rom-2a",
    chosenLabel: "Offer to explain the plot",
    chosenType: "safe",
    text: "She sat down beside him and talked for ten minutes straight. He listened with complete attention and said almost nothing. When she finally stopped, he said: same time next Thursday? She missed the next train also.",
    wordCount: 36,
    startsChapter: false,
  },
  {
    id: "rom-3b",
    parentId: "rom-2a",
    chosenLabel: "Give him her copy instead",
    chosenType: "chaotic",
    text: "She reached into her bag and held it out: take this one, she said. I've already folded the best pages. He took it, looked at the bent corners, looked at her. She did not know what came over her. She walked away quickly.",
    wordCount: 43,
    startsChapter: false,
  },
  {
    id: "rom-3c",
    parentId: "rom-2b",
    chosenLabel: "Tell him why she really stayed",
    chosenType: "emotional",
    text: "He deserved the truth, she decided. She said: I missed the last four trains on purpose. He was quiet for a moment. Then he said: I know. I've been getting here early so I could wait. They both looked at their shoes.",
    wordCount: 42,
    startsChapter: false,
  },
  {
    id: "rom-3d",
    parentId: "rom-2b",
    chosenLabel: "Pretend it was an accident",
    chosenType: "safe",
    text: "Oh no, she said, too brightly, I can't believe I missed it again. He smiled like someone who understood exactly what was happening. Shall we get coffee while we wait? he said. There is no next train for an hour.",
    wordCount: 40,
    startsChapter: false,
  },
];

// ── horror: "What the House Kept" (6 nodes, 2 branches) ──────────────
const horrorNodes: DemoNode[] = [
  {
    id: "hor-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "The house had been in the family for four generations and everyone agreed it was a good house. It was warm in winter. The garden was productive. No one talked about the room at the end of the hall that could not be measured from outside.",
    wordCount: 46,
    startsChapter: true,
  },
  {
    id: "hor-2a",
    parentId: "hor-1",
    chosenLabel: "Measure the room from inside",
    chosenType: "risky",
    text: "Twelve feet by twelve feet inside. The exterior wall should have been eight. She measured twice, then a third time. The tape always said twelve. She started to laugh and could not make herself stop.",
    wordCount: 35,
    startsChapter: false,
  },
  {
    id: "hor-2b",
    parentId: "hor-1",
    chosenLabel: "Ask the oldest neighbour about it",
    chosenType: "safe",
    text: "Mrs. Brant was ninety-one and had lived across the lane since before the current owners' grandparents. She listened to the question without expression. Then: don't open the closet in that room. Her tea went cold while she explained.",
    wordCount: 38,
    startsChapter: false,
  },
  {
    id: "hor-3a",
    parentId: "hor-2a",
    chosenLabel: "Open the closet",
    chosenType: "chaotic",
    text: "Inside: coats that were not theirs, shoes that fit no one in the family, and a child's drawing pinned to the back wall. The drawing showed the house with a figure in every window. The figure in the hall window had no face.",
    wordCount: 43,
    startsChapter: false,
  },
  {
    id: "hor-3b",
    parentId: "hor-2a",
    chosenLabel: "Photograph the measurements",
    chosenType: "safe",
    text: "She uploaded the photos and compared them to the floor plan from the original deed. The discrepancy was clear. She sent everything to a structural engineer. He replied within minutes: I can not come to that property. Please do not contact me again.",
    wordCount: 43,
    startsChapter: false,
  },
  {
    id: "hor-3c",
    parentId: "hor-2b",
    chosenLabel: "Ask what happens if it is opened",
    chosenType: "emotional",
    text: "Mrs. Brant set down her cup. She said: the last person who opened it was your great-grandmother. She was a practical woman. After that she would not stay in the house after dark — not for the rest of her life.",
    wordCount: 41,
    startsChapter: false,
  },
  {
    id: "hor-3d",
    parentId: "hor-2b",
    chosenLabel: "Dismiss the warning and go home",
    chosenType: "chaotic",
    text: "She thanked Mrs. Brant and crossed the lane feeling foolish. The house was warm and quiet and entirely ordinary. She went to bed early. At 3 a.m. she woke to the sound of something measuring the hallway in careful, even steps.",
    wordCount: 41,
    startsChapter: false,
  },
];

// ── thriller: "The Contract" (6 nodes, 2 branches) ───────────────────
const thrillerNodes: DemoNode[] = [
  {
    id: "thr-1",
    parentId: null,
    chosenLabel: null,
    chosenType: null,
    text: "The USB drive had been taped inside a library book returned six months ago. No one had borrowed the book since. The drive contained a single file: a contract between a minister and a man who had supposedly died in 2019. Both signatures were verified.",
    wordCount: 45,
    startsChapter: true,
  },
  {
    id: "thr-2a",
    parentId: "thr-1",
    chosenLabel: "Take the file to a journalist",
    chosenType: "risky",
    text: "The journalist met her in a car park at 6 a.m. and was careful not to touch the drive. He scanned the contract on a burner device and did not speak for two minutes. Then: who else has seen this? She told him she was the first. He did not look relieved.",
    wordCount: 52,
    startsChapter: false,
  },
  {
    id: "thr-2b",
    parentId: "thr-1",
    chosenLabel: "Research the dead man",
    chosenType: "safe",
    text: "The obituary was thorough and verifiable and almost certainly fabricated — she could see it now she was looking. The date of death was three weeks after the contract was signed. The funeral home listed had closed the following month.",
    wordCount: 40,
    startsChapter: false,
  },
  {
    id: "thr-3a",
    parentId: "thr-2a",
    chosenLabel: "Let him publish immediately",
    chosenType: "chaotic",
    text: "The story was online by noon. By two o'clock, her name was on the front page — not as a source, but as a suspect. The minister had moved first. He had a simpler story and he had told it to everyone who mattered.",
    wordCount: 44,
    startsChapter: false,
  },
  {
    id: "thr-3b",
    parentId: "thr-2a",
    chosenLabel: "Wait for corroboration",
    chosenType: "safe",
    text: "They waited four days. On the fifth morning, she woke to a text from a number she did not know: stop looking. She checked her front door. An envelope had been pushed through: the contract, with her address written on the back in someone else's handwriting.",
    wordCount: 46,
    startsChapter: false,
  },
  {
    id: "thr-3c",
    parentId: "thr-2b",
    chosenLabel: "Contact the dead man directly",
    chosenType: "emotional",
    text: "She found a forwarding address buried in a property record. She wrote a letter by hand and sent it that afternoon. Three days later, she received a reply: I wondered when someone would find that drive. I put it there myself. Let us meet.",
    wordCount: 44,
    startsChapter: false,
  },
  {
    id: "thr-3d",
    parentId: "thr-2b",
    chosenLabel: "Visit the closed funeral home",
    chosenType: "risky",
    text: "The building was boarded but not locked. Inside she found filing cabinets, mostly empty. One drawer held a single folder: the dead man's file. The cause of death was blank. The attending signature belonged to the minister.",
    wordCount: 37,
    startsChapter: false,
  },
];

export const DEMO_TREES: Record<string, DemoTree> = {
  hero: {
    title: "The Pale Book",
    nodes: heroNodes,
  },
  features: {
    title: "The Letter",
    nodes: featuresNodes,
  },
  fantasy: {
    title: "The Oath of Embers",
    nodes: fantasyNodes,
  },
  scifi: {
    title: "Signal from the Fold",
    nodes: scifiNodes,
  },
  mystery: {
    title: "The Missing Hour",
    nodes: mysteryNodes,
  },
  romance: {
    title: "One Platform Apart",
    nodes: romanceNodes,
  },
  horror: {
    title: "What the House Kept",
    nodes: horrorNodes,
  },
  thriller: {
    title: "The Contract",
    nodes: thrillerNodes,
  },
};
