import { Navbar } from "@/components/Navbar";
import Footer from "@/components/Footer";
import SEO from "@/components/SEO";

export default function Legal() {
  return (
    <div className="min-h-screen bg-background transition-colors duration-500">
      <SEO
        title="Terms of Service & Privacy Policy — Arcwrite"
        description="Arcwrite's terms of service and privacy policy. Learn how we handle your data and the rules that govern use of our platform."
        canonical="/legal"
      />
      <Navbar />

      <main className="pt-28 pb-20 px-6">
        <div className="max-w-2xl mx-auto">
          <h1 className="font-story text-3xl md:text-4xl font-semibold text-foreground mb-4">
            Terms &amp; Privacy
          </h1>
          <p className="text-sm text-muted-foreground mb-12">
            Last updated: April 13, 2026
          </p>

          {/* ─── Terms of Service ─── */}
          <section id="terms" className="mb-16 scroll-mt-28">
            <h2 className="font-story text-2xl font-semibold text-foreground mb-6">
              Terms of Service
            </h2>
            <div className="space-y-4 text-muted-foreground leading-relaxed text-[15px]">
              <p>
                By accessing or using Arcwrite (<span className="text-foreground">arcwrite.app</span>),
                you agree to be bound by these terms. If you do not agree, please do not use the service.
              </p>

              <h3 className="text-foreground font-medium pt-2">1. Service Description</h3>
              <p>
                Arcwrite is an AI-assisted interactive fiction platform. You provide creative direction
                and the service generates story text, choices, and related content using artificial
                intelligence. Arcwrite is operated by Silvergrain.
              </p>

              <h3 className="text-foreground font-medium pt-2">2. Accounts</h3>
              <p>
                You must create an account to use Arcwrite. You are responsible for maintaining the
                security of your account credentials. You must be at least 13 years old to use the
                service.
              </p>

              <h3 className="text-foreground font-medium pt-2">3. Your Content</h3>
              <p>
                You retain ownership of the creative direction and input you provide. Stories generated
                through Arcwrite are yours to use, share, and publish. We do not claim ownership of
                your stories or creative output.
              </p>

              <h3 className="text-foreground font-medium pt-2">4. Acceptable Use</h3>
              <p>
                You agree not to use Arcwrite to generate content that is illegal, promotes violence
                or harm, infringes on third-party rights, or attempts to abuse or disrupt the service.
                We reserve the right to suspend accounts that violate these terms.
              </p>

              <h3 className="text-foreground font-medium pt-2">5. Subscriptions &amp; Billing</h3>
              <p>
                Arcwrite offers free and paid subscription tiers. Paid plans are billed through Stripe.
                You may cancel at any time; cancellation takes effect at the end of the current billing
                period. Refunds are handled on a case-by-case basis.
              </p>

              <h3 className="text-foreground font-medium pt-2">6. AI-Generated Content</h3>
              <p>
                Content generated by AI may not always be accurate, appropriate, or aligned with your
                intent. You are responsible for reviewing and editing generated content before sharing
                or publishing it.
              </p>

              <h3 className="text-foreground font-medium pt-2">7. Service Availability</h3>
              <p>
                We strive to keep Arcwrite available but do not guarantee uninterrupted access. We may
                modify, suspend, or discontinue features with reasonable notice. We are not liable for
                any loss resulting from service interruptions.
              </p>

              <h3 className="text-foreground font-medium pt-2">8. Limitation of Liability</h3>
              <p>
                Arcwrite is provided "as is" without warranties of any kind. To the fullest extent
                permitted by law, Silvergrain shall not be liable for any indirect, incidental, or
                consequential damages arising from your use of the service.
              </p>

              <h3 className="text-foreground font-medium pt-2">9. Changes to Terms</h3>
              <p>
                We may update these terms from time to time. Continued use of Arcwrite after changes
                constitutes acceptance of the updated terms. Material changes will be communicated via
                email or in-app notification.
              </p>
            </div>
          </section>

          {/* ─── Privacy Policy ─── */}
          <section id="privacy" className="scroll-mt-28">
            <h2 className="font-story text-2xl font-semibold text-foreground mb-6">
              Privacy Policy
            </h2>
            <div className="space-y-4 text-muted-foreground leading-relaxed text-[15px]">
              <p>
                This policy describes how Arcwrite collects, uses, and protects your information.
              </p>

              <h3 className="text-foreground font-medium pt-2">1. Information We Collect</h3>
              <p>
                <span className="text-foreground">Account information:</span> When you sign up, we
                collect your name, email address, and profile picture through your authentication
                provider (Google or email/password via Clerk).
              </p>
              <p>
                <span className="text-foreground">Story data:</span> The stories you create, including
                text, choices, and creative settings, are stored in our database to provide the service.
              </p>
              <p>
                <span className="text-foreground">Usage data:</span> We collect basic analytics
                (page views, feature usage) through Vercel Analytics to improve the product. This data
                is aggregated and not personally identifiable.
              </p>
              <p>
                <span className="text-foreground">Payment information:</span> If you subscribe to a
                paid plan, payment details are processed and stored by Stripe. We do not store your
                credit card number.
              </p>

              <h3 className="text-foreground font-medium pt-2">2. How We Use Your Information</h3>
              <p>We use your information to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Provide and maintain the Arcwrite service</li>
                <li>Authenticate your identity and secure your account</li>
                <li>Process subscription payments</li>
                <li>Send service-related communications (e.g., account updates)</li>
                <li>Improve the product based on aggregated usage patterns</li>
              </ul>
              <p>
                We do <span className="text-foreground font-medium">not</span> sell your personal
                information to third parties. We do not use your story content to train AI models.
              </p>

              <h3 className="text-foreground font-medium pt-2">3. Third-Party Services</h3>
              <p>Arcwrite uses the following third-party services that may process your data:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li><span className="text-foreground">Clerk</span> — authentication and account management</li>
                <li><span className="text-foreground">OpenAI</span> — AI text generation (story content is sent to generate responses)</li>
                <li><span className="text-foreground">Stripe</span> — payment processing</li>
                <li><span className="text-foreground">Vercel</span> — hosting and analytics</li>
              </ul>
              <p>
                Each service operates under its own privacy policy. We encourage you to review them.
              </p>

              <h3 className="text-foreground font-medium pt-2">4. Data Storage &amp; Security</h3>
              <p>
                Your data is stored on secured servers. We use encryption in transit (HTTPS) and
                follow industry-standard security practices. Access to production data is restricted
                to authorized personnel only.
              </p>

              <h3 className="text-foreground font-medium pt-2">5. Data Retention</h3>
              <p>
                Your account and story data are retained as long as your account is active. If you
                delete your account, we will remove your personal data and stories within 30 days.
                Some data may be retained in backups for a limited period.
              </p>

              <h3 className="text-foreground font-medium pt-2">6. Your Rights</h3>
              <p>You have the right to:</p>
              <ul className="list-disc pl-6 space-y-1">
                <li>Access the personal data we hold about you</li>
                <li>Request correction of inaccurate data</li>
                <li>Request deletion of your account and data</li>
                <li>Export your stories</li>
              </ul>
              <p>
                To exercise any of these rights, contact us
                at <a href="mailto:support@arcwrite.app" className="text-primary hover:underline">support@arcwrite.app</a>.
              </p>

              <h3 className="text-foreground font-medium pt-2">7. Cookies</h3>
              <p>
                Arcwrite uses essential cookies for authentication and session management. We do not
                use tracking cookies or third-party advertising cookies.
              </p>

              <h3 className="text-foreground font-medium pt-2">8. Children's Privacy</h3>
              <p>
                Arcwrite is not intended for children under 13. We do not knowingly collect personal
                information from children under 13. If we become aware that we have collected data
                from a child under 13, we will delete it promptly.
              </p>

              <h3 className="text-foreground font-medium pt-2">9. Changes to This Policy</h3>
              <p>
                We may update this privacy policy from time to time. Changes will be posted on this
                page with an updated date. Continued use of Arcwrite constitutes acceptance of the
                revised policy.
              </p>

              <h3 className="text-foreground font-medium pt-2">10. Contact</h3>
              <p>
                For questions about these terms or your privacy, contact us
                at <a href="mailto:support@arcwrite.app" className="text-primary hover:underline">support@arcwrite.app</a>.
              </p>
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
